version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.30
    - 14.14.34
    - 15.0.0
  - dependency-name: next-pwa
    versions:
    - 5.1.4
    - 5.2.1
    - 5.2.14
    - 5.2.3
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
  - dependency-name: "@storybook/react"
    versions:
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: styled-components
    versions:
    - 5.2.2
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.20.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.20.0
  - dependency-name: next
    versions:
    - 10.1.2
  - dependency-name: husky
    versions:
    - 5.1.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.17
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.17
  - dependency-name: typescript
    versions:
    - 4.1.4
